import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiJquery,
  SiStorybook,
  SiMui,
  SiStyledcomponents,
  SiTailwindcss,
  SiVite,
  SiBootstrap,
  SiIonic,
  SiNodedotjs,
  SiNestjs,
  SiPhp,
  SiPython,
  SiDotnet,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiFirebase,
  SiSupabase,
  SiGraphql,
  SiDocker,
  SiKubernetes,
  SiAmazon,
  SiGooglecloud,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiGit,
  SiGithub,
  SiGitlab,
  SiBitbucket,
  SiJira,
  SiConfluence,
  SiTrello,
  SiSlack,
  SiDiscord,
  SiZoom,
  SiIntellijidea,
  SiWebstorm,
  SiPycharm,
  SiPostman,
  SiInsomnia,
  SiFigma,
  SiAdobexd,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiAdobepremierepro,
  SiAdobeaftereffects,
  SiTypescript,
  SiGo,
  SiApache,
  SiNginx,
  SiLens,
  SiNpm,
  SiYarn,
  SiApachemaven,
  SiRust,
  SiBun,
  SiPypi,
  SiCanva,
  SiAbstract,
  SiShopify,
  SiWordpress,
  SiWoocommerce,
  SiMagento,
  SiGooglesheets,
  SiGoogledocs,
  SiGoogledrive,
  SiGooglecalendar,
  SiNotion,
  SiDropbox,
  SiThunderbird,
  SiGoogleanalytics,
  SiGoogletagmanager,
  SiFacebook,
  SiMailchimp,
  SiUbuntu,
  SiMacos,
  SiDebian,
  SiManjaro,
  SiLinux,
  SiSwagger,
  SiPrisma,
  SiTerraform,
} from "react-icons/si";
import {
  FaJava,
  FaMicrosoft,
  FaStore,
  FaDigitalOcean,
  FaFileWord,
  FaFileExcel,
  FaFilePowerpoint,
} from "react-icons/fa";
import { VscAzure, VscVscode } from "react-icons/vsc";
import { BsMicrosoftTeams } from "react-icons/bs";
import { PiMicrosoftOutlookLogoFill } from "react-icons/pi";
import { Code2 } from "lucide-react";

export const skillIcons = {
  SiHtml5: { icon: SiHtml5, color: "#E34F26" },
  SiCss3: { icon: SiCss3, color: "#1572B6" },
  SiJavascript: { icon: SiJavascript, color: "#F7DF1E" },
  SiReact: { icon: SiReact, color: "#61DAFB" },
  SiNextdotjs: { icon: SiNextdotjs, color: "currentColor" },
  SiVuedotjs: { icon: SiVuedotjs, color: "#4FC08D" },
  SiJquery: { icon: SiJquery, color: "#0769AD" },
  SiStorybook: { icon: SiStorybook, color: "#FF4785" },
  SiMui: { icon: SiMui, color: "#007FFF" },
  SiStyledcomponents: { icon: SiStyledcomponents, color: "#DB7093" },
  SiTailwindcss: { icon: SiTailwindcss, color: "#06B6D4" },
  SiVite: { icon: SiVite, color: "#646CFF" },
  SiBootstrap: { icon: SiBootstrap, color: "#7952B3" },
  SiIonic: { icon: SiIonic, color: "#3880FF" },
  SiNodedotjs: { icon: SiNodedotjs, color: "#339933" },
  SiNestjs: { icon: SiNestjs, color: "#E0234E" },
  SiPhp: { icon: SiPhp, color: "#777BB4" },
  FaJava: { icon: FaJava, color: "#007396" },
  SiPython: { icon: SiPython, color: "#3776AB" },
  SiDotnet: { icon: SiDotnet, color: "#512BD4" },
  SiMysql: { icon: SiMysql, color: "#4479A1" },
  SiPostgresql: { icon: SiPostgresql, color: "#336791" },
  SiMongodb: { icon: SiMongodb, color: "#47A248" },
  SiRedis: { icon: SiRedis, color: "#DC382D" },
  SiFirebase: { icon: SiFirebase, color: "#FFCA28" },
  SiSupabase: { icon: SiSupabase, color: "#3ECF8E" },
  SiGraphql: { icon: SiGraphql, color: "#E10098" },
  SiDocker: { icon: SiDocker, color: "#2496ED" },
  SiKubernetes: { icon: SiKubernetes, color: "#326CE5" },
  SiTerraform: { icon: SiTerraform, color: "#623CE4" },
  SiAmazon: { icon: SiAmazon, color: "#FF9900" },
  SiGooglecloud: { icon: SiGooglecloud, color: "#4285F4" },
  FaDigitalOcean: { icon: FaDigitalOcean, color: "#0080FF" },
  VscAzure: { icon: VscAzure, color: "#0078D4" },
  SiGit: { icon: SiGit, color: "#F05032" },
  SiGithub: { icon: SiGithub, color: "currentColor" },
  SiGitlab: { icon: SiGitlab, color: "#FC6D26" },
  SiBitbucket: { icon: SiBitbucket, color: "#0052CC" },
  SiJira: { icon: SiJira, color: "#0052CC" },
  SiConfluence: { icon: SiConfluence, color: "#0052CC" },
  SiTrello: { icon: SiTrello, color: "#0052CC" },
  SiSlack: { icon: SiSlack, color: "currentColor" },
  SiDiscord: { icon: SiDiscord, color: "#5865F2" },
  SiZoom: { icon: SiZoom, color: "#2D8CFF" },
  BsMicrosoftTeams: { icon: BsMicrosoftTeams, color: "#6264A7" },
  VscVscode: { icon: VscVscode, color: "#007ACC" },
  SiIntellijidea: { icon: SiIntellijidea, color: "#e31a96ff" },
  SiWebstorm: { icon: SiWebstorm, color: "#45b8ffff" },
  SiPycharm: { icon: SiPycharm, color: "currentColor" },
  SiPostman: { icon: SiPostman, color: "#FF6C37" },
  SiInsomnia: { icon: SiInsomnia, color: "#4000BF" },
  SiFigma: { icon: SiFigma, color: "#F24E1E" },
  SiAdobexd: { icon: SiAdobexd, color: "#FF61F6" },
  SiAdobephotoshop: { icon: SiAdobephotoshop, color: "#31A8FF" },
  SiAdobeillustrator: { icon: SiAdobeillustrator, color: "#FF9A00" },
  SiAdobepremierepro: { icon: SiAdobepremierepro, color: "#9999FF" },
  SiAdobeaftereffects: { icon: SiAdobeaftereffects, color: "#9999FF" },
  SiTypescript: { icon: SiTypescript, color: "#3178C6" },
  SiVercel: { icon: SiVercel, color: "currentColor" },
  SiNetlify: { icon: SiNetlify, color: "#00C7B7" },
  SiHeroku: { icon: SiHeroku, color: "#430098" },
  FaMicrosoft: { icon: FaMicrosoft, color: "#00A4EF" },
  SiGo: { icon: SiGo, color: "#00ADD8" },
  SiApache: { icon: SiApache, color: "#D22128" },
  SiNginx: { icon: SiNginx, color: "#009639" },
  SiLens: { icon: SiLens, color: "#3D90CE" },
  SiNpm: { icon: SiNpm, color: "#CB3837" },
  SiYarn: { icon: SiYarn, color: "#2C8EBB" },
  SiApachemaven: { icon: SiApachemaven, color: "#C71A36" },
  SiRust: { icon: SiRust, color: "currentColor" },
  SiBun: { icon: SiBun, color: "currentColor" },
  SiPypi: { icon: SiPypi, color: "#3775A9" },
  SiCanva: { icon: SiCanva, color: "#00C4CC" },
  SiAbstract: { icon: SiAbstract, color: "currentColor" },
  SiShopify: { icon: SiShopify, color: "#7AB55C" },
  FaStore: { icon: FaStore, color: "currentColor" },
  SiWordpress: { icon: SiWordpress, color: "#21759B" },
  SiWoocommerce: { icon: SiWoocommerce, color: "#96588A" },
  SiMagento: { icon: SiMagento, color: "#EE672F" },
  SiGooglesheets: { icon: SiGooglesheets, color: "#34A853" },
  SiGoogledocs: { icon: SiGoogledocs, color: "#4285F4" },
  SiGoogledrive: { icon: SiGoogledrive, color: "#4285F4" },
  SiGooglecalendar: { icon: SiGooglecalendar, color: "#4285F4" },
  SiNotion: { icon: SiNotion, color: "currentColor" },
  SiDropbox: { icon: SiDropbox, color: "#0061FF" },
  SiThunderbird: { icon: SiThunderbird, color: "#0A84FF" },
  SiGoogleanalytics: { icon: SiGoogleanalytics, color: "#E37400" },
  SiGoogletagmanager: { icon: SiGoogletagmanager, color: "#246FDB" },
  SiFacebook: { icon: SiFacebook, color: "#1877F2" },
  SiMailchimp: { icon: SiMailchimp, color: "currentColor" },
  SiUbuntu: { icon: SiUbuntu, color: "#E95420" },
  SiMacos: { icon: SiMacos, color: "currentColor" },
  SiDebian: { icon: SiDebian, color: "#A81D33" },
  FaMicrosoftWindows: { icon: FaMicrosoft, color: "#0078D6" },
  SiManjaro: { icon: SiManjaro, color: "#35BF5C" },
  SiLinux: { icon: SiLinux, color: "currentColor" },
  SiSwagger: { icon: SiSwagger, color: "#85EA2D" },
  SiPrisma: { icon: SiPrisma, color: "currentColor" },
  FaFileWord: { icon: FaFileWord, color: "#2B579A" },
  FaFileExcel: { icon: FaFileExcel, color: "#217346" },
  FaFilePowerPoint: { icon: FaFilePowerpoint, color: "#D24726" },
  PiMicrosoftOutlookLogoFill: {
    icon: PiMicrosoftOutlookLogoFill,
    color: "#0078D4",
  },
};

export type SkillIconName = keyof typeof skillIcons;

export const getSkillIcon = (name: string) => {
  return (
    skillIcons[name as SkillIconName] || { icon: Code2, color: "currentColor" }
  );
};
